/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bigstep_Helium */

#ifndef _Included_com_bigstep_Helium
#define _Included_com_bigstep_Helium
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bigstep_Helium
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_bigstep_Helium_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_bigstep_Helium
 * Method:    insert
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_bigstep_Helium_insert
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_bigstep_Helium
 * Method:    exists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_bigstep_Helium_exists
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_bigstep_Helium
 * Method:    lookup
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bigstep_Helium_lookup
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_bigstep_Helium
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_bigstep_Helium_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
